os: linux
language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
go_import_path: gogs.io/gogs

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev

script:
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
