language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev

script:
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
