name: Shell
on:
  push:
    branches: [master, feature/*]
  pull_request:
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        continue-on-error: true
        # upstream changes need to be introduced to properly address the issues at a later point.
        # refs: https://github.com/G-Node/gogs/commit/11b31e5be31252a901ce0f7f79c026396e0f59aa
